### ISSUE TITLE
Try to modify navbar

### ISSUE THREAD

**Issue by dharmesh-poriya** [PRINCE-DHAMECHA/musicify#2]
Browse to countries, discover navlink color doesn't change.

**Comment by FilipePfluck** [comment]
Can you assign me?

**Comment by Dharmesh-Poriya07** [comment]
> Can you assign me?
yup

**Comment by dharmesh-poriya** [comment]
yes @FilipePfluck

**Comment by FilipePfluck** [comment]
Hey @Dharmesh-Poriya07 I created the PR https://github.com/developer-student-clubs/musicify/pull/6

**Comment by dharmesh-poriya** [comment]
bug fixed by @FilipePfluck
